config/routes.rb
Rails.application.routes.draw do
  resources :monologues, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  root 'top#index'

end

app/models/monologue.rb
class Monologue < ActiveRecord::Base
  validates :content, presence: true, length: { in: 0..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monologues_controller.rb
class MonologuesController < ApplicationController
  before_action :set_monologue, only: [:edit, :update, :destroy]

  def index
    @monologues = Monologue.order(:created_at).reverse_order
  end

  def new
    if params[:back]
      @monologue = Monologue.new(monologues_params)
    else
      @monologue = Monologue.new
    end
  end

  def create
    @monologue = Monologue.create(monologues_params)
    if @monologue.save
      redirect_to monologues_path, notice: "ひとりごとしました！"
    else
      render 'new'
    end
  end

  def edit
    @monologue = Monologue.find(params[:id])
  end

  def update
    @monologue = Monologue.find(params[:id])
    if @monologue.update(monologues_params)
      redirect_to monologues_path, notice: "更新しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @monologue = Monologue.find(params[:id])
    @monologue.destroy
    redirect_to monologues_path, notice: "削除しました！"
  end

  def confirm
    @monologue = Monologue.new(monologues_params)
    render :new if @monologue.invalid?
  end

  private
    def monologues_params
      params.require(:monologue).permit(:content)
    end

    def set_monologue
      @monologue = Monologue.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monologues_helper.rb
module MonologuesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_monologues_path
    elsif action_name == 'edit'
      monologue_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EXAM1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div id="leftContents">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "ホーム", root_path, class: 'navbar-brand' %>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ひとりごとが気になる方は<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "ひとりごとリスト", monologues_path %></li>
              <li><%= link_to "ひとりごとする", new_monologue_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<%= yield %>

</body>
</html>

app/views/monologues/_form.html.erb
  <h2>ひとりごと</h2>
  <%= form_for(@monologue, url: choose_new_or_edit) do |f| %>
    <% if @monologue.errors.any? %>
      <div id="error_explanation">
        <h2><%= @monologue.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @monologue.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_area :content,:size => "40x5" %>
    <br>
    <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
  <% end %>

app/views/monologues/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1 content">

  <h3>以下の内容でひとりごとする。</h3>

  <%= form_for(@monologue) do |f| %>
    <%= f.hidden_field :content %>
    <h3><%= @monologue.content %></h3>
    <%= f.submit "ひとりごとする",class: 'btn btn-primary btn-block' %>
  <% end %>

  <%= form_for(@monologue, url: new_monologue_path, method: 'get') do |f| %>
    <%= f.hidden_field :content %>
    <%= f.submit "もどる", name: 'back',class: 'btn btn-default btn-block' %>
  <% end %>
  </div>
</div>
  

app/views/monologues/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1 content">
    <%= render 'form' %>
  </div>
</div>

app/views/monologues/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4" id="monologue_text">
        <h3>ひとりごとするアプリ</h3>
        <p>ruby on railsサンプルアプリケーション</p>
        <p>今までのひとりごとリスト</p>
        <p></p>
        <p><%= link_to "ひとりごとする", new_monologue_path %></p>
    </div>
    <div class="col-sm-8">
      <div id="monologue_list">
        <% @monologues.each do |monologue| %>
        <div id="monologue">
          <h3><%= monologue.content %></h3><%= monologue.created_at.strftime('%Y年%m月%d日 %H:%M') %>
          <div id="button">
          <%= link_to "編集", edit_monologue_path(monologue.id), class: 'btn btn-default btn-sm btn-primary' %>
          <%= link_to "削除", monologue_path(monologue.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-default btn-sm btn-warning' %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/monologues/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1 content">
    <%= render 'form' %>
  </div>
</div>

app/views/top/index.html.erb
<div class="container" id="top_page">
  <div class="row">
    <div class="col-sm-6" id="top">
        <h2>ひとりごとするアプリ</h2>
        <p>ruby on railsサンプルアプリケーション</p>
    </div>
    <div class="col-sm-6" id="devices"><img src="<%= asset_path "devices.png" %>" width="50%"></div>
  </div>
</div>